const fs = require("fs");
const p = "components/gold-page.tsx";
let c = fs.readFileSync(p, "utf8");
const NL = "\r\n";

const lines = [];
lines.push("");
lines.push("          {/* ========== Ingot Calculator ========== */}");
lines.push('          <Card className="mb-8 border-yellow-500/20 bg-gradient-to-br from-yellow-500/5 to-amber-600/5">');
lines.push("            <CardHeader>");
lines.push('              <div className="flex items-center gap-3">');
lines.push('                <div className="flex h-11 w-11 items-center justify-center rounded-xl bg-yellow-500/10">');
lines.push('                  <Calculator className="h-6 w-6 text-yellow-500" />');
lines.push("                </div>");
lines.push("                <div>");
lines.push('                  <CardTitle className="text-lg">{tc("title")}</CardTitle>');
lines.push('                  <p className="text-sm text-muted-foreground">{tc("subtitle")}</p>');
lines.push("                </div>");
lines.push("              </div>");
lines.push("            </CardHeader>");
lines.push('            <CardContent className="space-y-6">');
lines.push("              {/* Karat Selection */}");
lines.push("              <div>");
lines.push('                <Label className="mb-2 block text-sm font-medium">{tc("selectKarat")}</Label>');
lines.push('                <div className="flex flex-wrap gap-2">');
lines.push("                  {([24, 21, 18]).map((k) => (");
lines.push("                    <Button");
lines.push("                      key={k}");
lines.push('                      variant={selectedKarat === k ? "default" : "outline"}');
lines.push('                      className={selectedKarat === k ? "bg-yellow-500 text-black hover:bg-yellow-600" : "border-yellow-500/30 hover:bg-yellow-500/10"}');
lines.push("                      onClick={() => setSelectedKarat(k)}");
lines.push("                    >");
lines.push('                      {k}K {k === 24 ? tc("pure") : ""}');
lines.push("                    </Button>");
lines.push("                  ))}");
lines.push("                </div>");
lines.push("              </div>");
lines.push("");
lines.push("              {/* Weight Selection */}");
lines.push("              <div>");
lines.push('                <Label className="mb-2 block text-sm font-medium">{tc("selectWeight")}</Label>');
lines.push('                <div className="flex flex-wrap gap-2">');
lines.push("                  {standardWeights.map((w) => (");
lines.push("                    <Button");
lines.push("                      key={w}");
lines.push('                      size="sm"');
lines.push('                      variant={selectedWeight === w && !customWeight ? "default" : "outline"}');
lines.push('                      className={selectedWeight === w && !customWeight ? "bg-yellow-500 text-black hover:bg-yellow-600" : "border-yellow-500/30 hover:bg-yellow-500/10"}');
lines.push('                      onClick={() => { setSelectedWeight(w); setCustomWeight(""); }}');
lines.push("                    >");
lines.push('                      {w === 31.1035 ? "1 oz" : w + "g"}');
lines.push("                    </Button>");
lines.push("                  ))}");
lines.push("                </div>");
lines.push('                <div className="mt-3 flex items-center gap-2">');
lines.push("                  <Input");
lines.push('                    type="number"');
lines.push('                    min="0.1"');
lines.push('                    step="0.1"');
lines.push('                    placeholder={tc("customWeightPlaceholder")}');
lines.push("                    value={customWeight}");
lines.push("                    onChange={(e) => setCustomWeight(e.target.value)}");
lines.push('                    className="max-w-[200px] border-yellow-500/30 focus-visible:ring-yellow-500/50"');
lines.push("                  />");
lines.push('                  <span className="text-sm text-muted-foreground">g</span>');
lines.push("                </div>");
lines.push("              </div>");
lines.push("");
lines.push("              {/* Results */}");
lines.push("              {calcResults && (");
lines.push('                <div className="rounded-lg border border-yellow-500/20 bg-yellow-500/5 p-4 space-y-3">');
lines.push('                  <div className="grid grid-cols-2 gap-4">');
lines.push("                    <div>");
lines.push('                      <p className="text-xs text-muted-foreground">{tc("pricePerGram")}</p>');
lines.push('                      <p className="text-lg font-bold text-foreground">{formatEGP(calcResults.pricePerGram)} EGP</p>');
lines.push("                    </div>");
lines.push("                    <div>");
lines.push('                      <p className="text-xs text-muted-foreground">{tc("pricePerGramUSD")}</p>');
lines.push('                      <p className="text-lg font-bold text-foreground">{formatUSD(calcResults.pricePerGramUSD)}</p>');
lines.push("                    </div>");
lines.push("                  </div>");
lines.push('                  <div className="border-t border-yellow-500/20 pt-3 grid grid-cols-2 gap-4">');
lines.push("                    <div>");
lines.push('                      <p className="text-xs text-muted-foreground">{tc("totalPriceEGP")} ({activeWeight}g)</p>');
lines.push('                      <p className="text-2xl font-bold text-yellow-500">{formatEGP(calcResults.totalEGP)} EGP</p>');
lines.push("                    </div>");
lines.push("                    <div>");
lines.push('                      <p className="text-xs text-muted-foreground">{tc("totalPriceUSD")}</p>');
lines.push('                      <p className="text-xl font-bold text-foreground">{formatUSD(calcResults.totalUSD)}</p>');
lines.push("                    </div>");
lines.push("                  </div>");
lines.push("                </div>");
lines.push("              )}");
lines.push("");
lines.push("              {/* Comparison Table */}");
lines.push("              {comparisonRows.length > 0 && (");
lines.push("                <div>");
lines.push('                  <div className="flex items-center gap-2 mb-2">');
lines.push('                    <ArrowRightLeft className="h-4 w-4 text-yellow-500" />');
lines.push('                    <span className="text-sm font-medium">{tc("gold")} {activeWeight}g</span>');
lines.push("                  </div>");
lines.push('                  <div className="rounded-lg border border-border overflow-hidden">');
lines.push('                    <table className="w-full text-sm">');
lines.push("                      <thead>");
lines.push('                        <tr className="border-b border-border bg-muted/50">');
lines.push('                          <th className="px-4 py-2 text-left font-medium">{tc("karat")}</th>');
lines.push('                          <th className="px-4 py-2 text-right font-medium">{tc("priceEGP")}</th>');
lines.push('                          <th className="px-4 py-2 text-right font-medium">{tc("priceUSD")}</th>');
lines.push("                        </tr>");
lines.push("                      </thead>");
lines.push("                      <tbody>");
lines.push("                        {comparisonRows.map((row) => (");
lines.push("                          <tr key={row.karat} className={`border-b border-border last:border-0 ${row.karat === selectedKarat ? \"bg-yellow-500/10\" : \"\"}`}>");
lines.push('                            <td className="px-4 py-2 font-medium">{row.karat}K</td>');
lines.push('                            <td className="px-4 py-2 text-right">{formatEGP(row.priceEGP)} EGP</td>');
lines.push('                            <td className="px-4 py-2 text-right">{formatUSD(row.priceUSD)}</td>');
lines.push("                          </tr>");
lines.push("                        ))}");
lines.push("                      </tbody>");
lines.push("                    </table>");
lines.push("                  </div>");
lines.push("                </div>");
lines.push("              )}");
lines.push("            </CardContent>");
lines.push("          </Card>");

const calcJSX = lines.join(NL);

const anchor = "          </div>" + NL + NL + "          <div className=\"grid gap-4 sm:grid-cols-2 lg:grid-cols-3 mb-8\">";
const replacement = "          </div>" + NL + calcJSX + NL + NL + "          <div className=\"grid gap-4 sm:grid-cols-2 lg:grid-cols-3 mb-8\">";

if (c.includes(anchor)) {
  c = c.replace(anchor, replacement);
  fs.writeFileSync(p, c, "utf8");
  console.log("Done. New line count:", c.split("\r\n").length);
  console.log("Has Calculator JSX:", c.includes("Ingot Calculator"));
} else {
  console.log("ERROR: anchor not found!");
  const idx = c.indexOf("grid gap-4 sm:grid-cols-2");
  console.log("grid index:", idx);
  if (idx > 0) console.log("around:", JSON.stringify(c.substring(idx - 60, idx + 10)));
}
